# ------------------- GITHUB ACTIONS WORKFLOW -------------------
name: Update Daily Cyber & Tech News Feed

on:
  schedule:
    - cron: '0 20 * * *'  # 6 AM AEST = 8 PM UTC daily
  workflow_dispatch:      # allows you to run manually from GitHub UI

permissions:
  contents: write  # gives permission to push changes

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install beautifulsoup4 lxml

      - name: Run news feed script
        run: python main.py

      - name: Commit and push changes
        run: |
          git config user.name 'github-actions'
          git config user.email 'actions@github.com'
          git add index.html
          git commit -m "📰 Daily update of tech news feed" || echo "No changes to commit"
          git push

